#!/bin/bash

POKEMON_LIST=("bulbasaur" "ivysaur" "venusaur" "charmander" "charmeleon")
BASE_API_URL="https://pokeapi.co/api/v2/pokemon"
LOGFILE="errors.txt"
DELAY=2

for pokemon in "${POKEMON_LIST[@]}"; do
    echo "Fetching data for $pokemon..."
    for i in {1..3}; do
      success=false
        HTTP_CODE=$(curl -s -w "%{http_code}" -o "${pokemon}.json" "${BASE_API_URL}/${pokemon}" 2>>"$LOGFILE")

        if [ "$HTTP_CODE" -eq 200 ]; then
            echo "Saved ${pokemon}.json"
            success=true
            break
        else
            echo "Retry #$i failed for $pokemon (HTTP code $HTTP_CODE)" >> "$LOGFILE"
            sleep 1
        fi
      done
    if [ "$success" = false ]; then
            echo "❌ Failed to fetch $pokemon after 3 attempts." >> "$LOGFILE"
    fi
    success=false
    sleep "$DELAY"
done

echo "All done!"
