#!/bin/bash

DATAFILE="pikachu_detail.json"

if [ ! -f "$DATAFILE" ]; then
  echo "Error: $DATAFILE not found!"
  exit 1
fi

name=$(jq -r '.name' "$DATAFILE")
type=$(jq -r '.types[0].type.name' "$DATAFILE")
weight_hecto=$(jq -r '.weight' "$DATAFILE")
height_deci=$(jq -r '.height' "$DATAFILE")

capitalize() {
  echo "$1" | awk '{print toupper(substr($0,1,1)) tolower(substr($0,2))}'
}

format_num() {
  local num=$1
  local formatted=$(echo "scale=1; $num / 10" | bc)
  echo "$formatted" | sed 's/\.0$//'
}

name=$(capitalize "$name")
type=$(capitalize "$type")

formatted_weight=$(format_num "$weight_hecto")
formatted_height=$(format_num "$height_deci")

echo "$name is of type $type, weighs ${formatted_weight}kg, and is ${formatted_height}m tall."
