#!/bin/bash

REPORT="pokemon_report.csv"
TEMPFILE="pokemon_data.tmp"

echo "Name,Height (m),Weight (kg)" > "$REPORT"


for jsonfile in *.json; do
  [ -e "$jsonfile" ] || { echo "No JSON files found."; exit 1; }

  name=$(jq -r '.name' "$jsonfile" | awk '{print toupper(substr($0,1,1)) tolower(substr($0,2))}')
  height_dm=$(jq -r '.height' "$jsonfile")
  weight_hg=$(jq -r '.weight' "$jsonfile")

  height=$(echo "scale=2; $height_dm / 10" | bc)
  weight=$(echo "scale=2; $weight_hg / 10" | bc)

  echo "$name,$height,$weight" >> "$REPORT"
  echo "$height $weight" >> "$TEMPFILE"
done

echo "CSV Report generated at: $REPORT"
echo

cat "$REPORT"
echo

read avg_height avg_weight <<< $(awk '{h+=$1; w+=$2; c++} END {printf "%.2f %.2f", h/c, w/c}' "$TEMPFILE")

echo "Average Height: $avg_height m"
echo "Average Weight: $avg_weight kg"

rm "$TEMPFILE"
